-- Migração: Atualizar organizations com setores
-- Extraído de Empresas_e_Setores.xlsx
-- Nomes das empresas foram limpos (removidos emojis, espaços extras, lembretes, etc.)
-- Empresas removidas: LinkedIn URL, Sport para Sport BR, Tirol
--
-- Este script:
-- 1. Insere organizações que não existem
-- 2. Atualiza sector_ids para todas as organizações baseado no mapeamento

-- Primeiro, garantir que as organizações existam
INSERT INTO organizations (name)
SELECT DISTINCT empresa_name
FROM (VALUES
    ('Adidas'),
    ('New Balance'),
    ('Columbia'),
    ('Nike'),
    ('ON Running'),
    ('Asics'),
    ('Salomon'),
    ('Havaianas'),
    ('Oakley'),
    ('Centauro'),
    ('Speedo'),
    ('Sigvaris'),
    ('The North Face'),
    ('Track & Field'),
    ('Óticas Carol'),
    ('Evoke'),
    ('HB - Hot Buttered'),
    ('La Sportiva'),
    ('Buff'),
    ('Kendall'),
    ('Compresssport'),
    ('Julbo Eyewear'),
    ('Inov8'),
    ('Under Armour'),
    ('Olympikus'),
    ('Osprey'),
    ('Garmin'),
    ('Sunnto'),
    ('Coros Global'),
    ('Camelbak'),
    ('GoPro'),
    ('Polar'),
    ('LG'),
    ('Huawei'),
    ('Petzl'),
    ('Café 3 Corações'),
    ('Sambazon Açaí'),
    ('Verde Campo'),
    ('Monster'),
    ('Red Bull'),
    ('Mãe Terra'),
    ('Positive Brands'),
    ('Sou Dobro'),
    ('Flormel'),
    ('Águas Petrópolis'),
    ('Mundo Verde'),
    ('Green Up'),
    ('Castelo Alimentos'),
    ('Águas Lindoya (Verão)'),
    ('Carrefour'),
    ('Frooty Açai'),
    ('Bio2'),
    ('OBA Hortifruti'),
    ('Minalba'),
    ('Hortifruti'),
    ('GPA - Grupo Pão de Açúcar'),
    ('Piracanjuba'),
    ('Gol'),
    ('KLM / Airfrance'),
    ('Bravo Açaí'),
    ('Buser'),
    ('Azul Linhas Aéreas'),
    ('Latam Airlines'),
    ('Nubank'),
    ('Santander'),
    ('XP Investimentos'),
    ('C6'),
    ('Mastercard'),
    ('BTG Pactual'),
    ('Caixa Econômica Federal'),
    ('Body Action'),
    ('ELO'),
    ('Atlhetica Nutrition'),
    ('Omint Seguradora'),
    ('Bradesco'),
    ('VISA'),
    ('Grupo Supley'),
    ('Porto Seguro'),
    ('Essential Nutrition'),
    ('Banco Original'),
    ('Integralmédica'),
    ('DUX Nutrition'),
    ('Vitafor'),
    ('GT Nutrition'),
    ('HouseWhey'),
    ('Exceed Nutrition'),
    ('Mother Nutrients'),
    ('GU Energy Labs'),
    ('Mitsubishi'),
    ('Localiza'),
    ('Audi'),
    ('Movida'),
    ('Uber'),
    ('Nissan'),
    ('Jeep (Grupo Stellantis)'),
    ('Strava'),
    ('Unidas'),
    ('Volkswagen'),
    ('Vivo'),
    ('Cia Athletica'),
    ('Smart Fit'),
    ('Oi'),
    ('Bodytech'),
    ('Tim'),
    ('Competition'),
    ('Decathlon'),
    ('Engie'),
    ('Cosan'),
    ('Mapfre'),
    ('MaDi'),
    ('Wilson Sons'),
    ('Turkish'),
    ('UnitedHealth Group'),
    ('Spot'),
    ('ADV Force'),
    ('Mixtura Fit'),
    ('Pacco'),
    ('Banco do Brasil'),
    ('GYMPASS'),
    ('Banco Safra'),
    ('Bold'),
    ('Parque Bondinho Pão de Açúcar'),
    ('Peak Sports'),
    ('Enel'),
    ('Petrobrás'),
    ('Shell'),
    ('OMRON Brazil'),
    ('Danone'),
    ('Authen'),
    ('Natural One'),
    ('Nhami Mami'),
    ('Curtlo'),
    ('Purela'),
    ('Sephora'),
    ('Nestlé'),
    ('Bluefit Academia'),
    ('Granado'),
    ('La Naturelle (Sorvetes naturais)'),
    ('O Boticário'),
    ('Simple Organic Beauty'),
    ('Care'),
    ('Green People'),
    ('Organifi'),
    ('Allianz'),
    ('Rolex'),
    ('Diadora'),
    ('Reebok'),
    ('Converse'),
    ('Hummel'),
    ('Claro'),
    ('Alelo'),
    ('Cielo'),
    ('Águas de Paraty'),
    ('Ambev'),
    ('Grupo Biophilia'),
    ('Netshoes'),
    ('Riô Biocosméticos'),
    ('Vitamine-se'),
    ('Águas Prata'),
    ('Patagônia'),
    ('Grupo Petrópolis'),
    ('My Safe Sport'),
    ('Eisenbahn'),
    ('Chilli Beans'),
    ('Cervejaria Cidade Imperial'),
    ('Intua'),
    ('Sallve'),
    ('Reunidas paulistas'),
    ('Johnson & Johnson'),
    ('Grupo DPSP (Drogarias SP e Pacheco)'),
    ('Meta'),
    ('Daki'),
    ('D-Local'),
    ('Vapza Alimentos'),
    ('Bauducco'),
    ('Continental'),
    ('ABSOLAR'),
    ('IFood'),
    ('Galderma'),
    ('Banco Hyundai Capital Brasil'),
    ('Rappi'),
    ('MG Sportswear'),
    ('Eco Skin'),
    ('Nomad'),
    ('Mombora'),
    ('Banco BMG'),
    ('Banco BV'),
    ('Mundo Terra'),
    ('Ajinomoto'),
    ('Better Drinks / Praya'),
    ('Replayers'),
    ('Stone'),
    ('Heineken Zero'),
    ('Água na Caixa'),
    ('Fuel Eyewear'),
    ('Eurofarma'),
    ('Globo'),
    ('Grupo DASA'),
    ('Comgás'),
    ('Yoppi'),
    ('Puro Verde'),
    ('Oakberry'),
    ('Sky'),
    ('Italac'),
    ('Caffeine Army'),
    ('Kaillash'),
    ('Juçaí'),
    ('Grupo Zanlorenzi (Campo Largo)'),
    ('Go Outside'),
    ('Águas do Rio'),
    ('Droga Raia'),
    ('Samsung'),
    ('PepsiCo'),
    ('Itaú'),
    ('Bradesco Seguros'),
    ('Tirolez'),
    ('Mondelēz International')
) AS t(empresa_name)
WHERE NOT EXISTS (
  SELECT 1 FROM organizations o WHERE LOWER(TRIM(o.name)) = LOWER(TRIM(t.empresa_name))
);

-- Agora, atualizar sector_ids usando CTE com mapeamento
WITH empresa_sectors_map AS (
  SELECT empresa_name, array_agg(sector_name ORDER BY sector_name) as sector_names
  FROM (VALUES
    ('Adidas', 'Technical sports Apparel'),
    ('New Balance', 'Technical sports Apparel'),
    ('Columbia', 'Technical sports Apparel'),
    ('Nike', 'Technical sports Apparel'),
    ('ON Running', 'Technical sports Apparel'),
    ('Asics', 'Technical sports Apparel'),
    ('Salomon', 'Technical sports Apparel'),
    ('Havaianas', 'Technical sports Apparel'),
    ('Oakley', 'Technical sports Apparel'),
    ('Centauro', 'Technical sports Apparel'),
    ('Speedo', 'Technical sports Apparel'),
    ('Sigvaris', 'Technical sports Apparel'),
    ('The North Face', 'Technical sports Apparel'),
    ('Track & Field', 'Technical sports Apparel'),
    ('Óticas Carol', 'Technical sports Apparel'),
    ('Evoke', 'Technical sports Apparel'),
    ('HB - Hot Buttered', 'Technical sports Apparel'),
    ('La Sportiva', 'Technical sports Apparel'),
    ('Buff', 'Technical sports Apparel'),
    ('Kendall', 'Technical sports Apparel'),
    ('Compresssport', 'Technical sports Apparel'),
    ('Julbo Eyewear', 'Technical sports Apparel'),
    ('Inov8', 'Technical sports Apparel'),
    ('Under Armour', 'Technical sports Apparel'),
    ('Olympikus', 'Technical sports Apparel'),
    ('Osprey', 'Technical sports Apparel'),
    ('Garmin', 'Sports retailers'),
    ('Sunnto', 'Sports retailers'),
    ('Coros Global', 'Sports retailers'),
    ('Camelbak', 'Sports retailers'),
    ('GoPro', 'Sports retailers'),
    ('Polar', 'Sports retailers'),
    ('LG', 'Sports retailers'),
    ('Huawei', 'Sports retailers'),
    ('Petzl', 'Sports retailers'),
    ('Café 3 Corações', 'Performance/Sports Drinks'),
    ('Sambazon Açaí', 'Performance/Sports Drinks'),
    ('Verde Campo', 'Performance/Sports Drinks'),
    ('Monster', 'Performance/Sports Drinks'),
    ('Red Bull', 'Performance/Sports Drinks'),
    ('Mãe Terra', 'Performance/Sports Drinks'),
    ('Positive Brands', 'Performance/Sports Drinks'),
    ('Sou Dobro', 'Performance/Sports Drinks'),
    ('Flormel', 'Performance/Sports Drinks'),
    ('Águas Petrópolis', 'Reusable water bottles'),
    ('Mundo Verde', 'Performance/Sports Drinks'),
    ('Green Up', 'Performance/Sports Drinks'),
    ('Castelo Alimentos', 'Performance/Sports Drinks'),
    ('Águas Lindoya (Verão)', 'Reusable water bottles'),
    ('Carrefour', 'Performance/Sports Drinks'),
    ('Frooty Açai', 'Performance/Sports Drinks'),
    ('Bio2', 'Performance/Sports Drinks'),
    ('OBA Hortifruti', 'Performance/Sports Drinks'),
    ('Minalba', 'Reusable water bottles'),
    ('Hortifruti', 'Performance/Sports Drinks'),
    ('GPA - Grupo Pão de Açúcar', 'Performance/Sports Drinks'),
    ('Piracanjuba', 'Performance/Sports Drinks'),
    ('Gol', 'Travel & accommodation services'),
    ('KLM / Airfrance', 'Travel & accommodation services'),
    ('Bravo Açaí', 'Performance/Sports Drinks'),
    ('Buser', 'Travel & accommodation services'),
    ('Azul Linhas Aéreas', 'Travel & accommodation services'),
    ('Latam Airlines', 'Travel & accommodation services'),
    ('Nubank', 'Financial services'),
    ('Santander', 'Financial services'),
    ('XP Investimentos', 'Financial services'),
    ('C6', 'Financial services'),
    ('Mastercard', 'Financial services'),
    ('BTG Pactual', 'Financial services'),
    ('Caixa Econômica Federal', 'Financial services'),
    ('Body Action', 'Energy Bars'),
    ('ELO', 'Financial services'),
    ('Atlhetica Nutrition', 'Energy Bars'),
    ('Omint Seguradora', 'Insurance'),
    ('Bradesco', 'Financial services'),
    ('VISA', 'Financial services'),
    ('Grupo Supley', 'Energy Bars'),
    ('Porto Seguro', 'Insurance'),
    ('Essential Nutrition', 'Energy Bars'),
    ('Banco Original', 'Financial services'),
    ('Integralmédica', 'Energy Bars'),
    ('DUX Nutrition', 'Energy Bars'),
    ('Vitafor', 'Energy Bars'),
    ('GT Nutrition', 'Energy Bars'),
    ('HouseWhey', 'Energy Bars'),
    ('Exceed Nutrition', 'Energy Bars'),
    ('Mother Nutrients', 'Energy Bars'),
    ('GU Energy Labs', 'Energy Bars'),
    ('Mitsubishi', 'Automaker (including electric cars)'),
    ('Localiza', 'Automaker (including electric cars)'),
    ('Audi', 'Automaker (including electric cars)'),
    ('Movida', 'Automaker (including electric cars)'),
    ('Nissan', 'Automaker (including electric cars)'),
    ('Jeep (Grupo Stellantis)', 'Automaker (including electric cars)'),
    ('Unidas', 'Automaker (including electric cars)'),
    ('Volkswagen', 'Automaker (including electric cars)'),
    ('Cia Athletica', 'Coaching application'),
    ('Smart Fit', 'Coaching application'),
    ('Bodytech', 'Coaching application'),
    ('Competition', 'Coaching application'),
    ('Mapfre', 'Insurance'),
    ('MaDi', 'Energy Bars'),
    ('Wilson Sons', 'Travel & accommodation services'),
    ('Turkish', 'Travel & accommodation services'),
    ('UnitedHealth Group', 'Insurance'),
    ('Spot', 'Sports retailers'),
    ('ADV Force', 'Technical sports Apparel'),
    ('Mixtura Fit', 'Performance/Sports Drinks'),
    ('Pacco', 'Sports retailers'),
    ('Banco do Brasil', 'Financial services'),
    ('GYMPASS', 'Coaching application'),
    ('Banco Safra', 'Financial services'),
    ('Bold', 'Performance/Sports Drinks'),
    ('Parque Bondinho Pão de Açúcar', 'Coaching application'),
    ('Peak Sports', 'Technical sports Apparel'),
    ('Petrobrás', 'Oil & Gas'),
    ('Shell', 'Oil & Gas'),
    ('OMRON Brazil', 'Sports retailers'),
    ('Danone', 'Performance/Sports Drinks'),
    ('Authen', 'Technical sports Apparel'),
    ('Natural One', 'Performance/Sports Drinks'),
    ('Nhami Mami', 'Performance/Sports Drinks'),
    ('Curtlo', 'Technical sports Apparel'),
    ('Purela', 'Personal care/cosmetics'),
    ('Sephora', 'Personal care/cosmetics'),
    ('Sephora', 'Technical sports Apparel'),
    ('Nestlé', 'Performance/Sports Drinks'),
    ('Bluefit Academia', 'Coaching application'),
    ('Granado', 'Personal care/cosmetics'),
    ('La Naturelle (Sorvetes naturais)', 'Performance/Sports Drinks'),
    ('O Boticário', 'Personal care/cosmetics'),
    ('Simple Organic Beauty', 'Personal care/cosmetics'),
    ('Care', 'Personal care/cosmetics'),
    ('Green People', 'Performance/Sports Drinks'),
    ('Organifi', 'Personal care/cosmetics'),
    ('Allianz', 'Insurance'),
    ('Diadora', 'Technical sports Apparel'),
    ('Reebok', 'Technical sports Apparel'),
    ('Converse', 'Technical sports Apparel'),
    ('Hummel', 'Technical sports Apparel'),
    ('Alelo', 'Financial services'),
    ('Cielo', 'Financial services'),
    ('Ambev', 'Performance/Sports Drinks'),
    ('Grupo Biophilia', 'Performance/Sports Drinks'),
    ('Netshoes', 'Technical sports Apparel'),
    ('Riô Biocosméticos', 'Personal care/cosmetics'),
    ('Vitamine-se', 'Energy Bars'),
    ('Águas Prata', 'Performance/Sports Drinks'),
    ('Patagônia', 'Performance/Sports Drinks'),
    ('Patagônia', 'Technical sports Apparel'),
    ('Grupo Petrópolis', 'Performance/Sports Drinks'),
    ('My Safe Sport', 'Coaching application'),
    ('Eisenbahn', 'Performance/Sports Drinks'),
    ('Chilli Beans', 'Eyewear'),
    ('Cervejaria Cidade Imperial', 'Performance/Sports Drinks'),
    ('Intua', 'Personal care/cosmetics'),
    ('Sallve', 'Personal care/cosmetics'),
    ('Reunidas paulistas', 'Travel & accommodation services'),
    ('Johnson & Johnson', 'Personal care/cosmetics'),
    ('Daki', 'Performance/Sports Drinks'),
    ('D-Local', 'Financial services'),
    ('Vapza Alimentos', 'Performance/Sports Drinks'),
    ('Bauducco', 'Performance/Sports Drinks'),
    ('IFood', 'Performance/Sports Drinks'),
    ('Banco Hyundai Capital Brasil', 'Financial services'),
    ('Rappi', 'Performance/Sports Drinks'),
    ('MG Sportswear', 'Technical sports Apparel'),
    ('Eco Skin', 'Personal care/cosmetics'),
    ('Nomad', 'Financial services'),
    ('Mombora', 'Energy Bars'),
    ('Banco BMG', 'Financial services'),
    ('Banco BV', 'Financial services'),
    ('Mundo Terra', 'Performance/Sports Drinks'),
    ('Ajinomoto', 'Performance/Sports Drinks'),
    ('Better Drinks / Praya', 'Performance/Sports Drinks'),
    ('Replayers', 'Sports retailers'),
    ('Stone', 'Financial services'),
    ('Heineken Zero', 'Performance/Sports Drinks'),
    ('Água na Caixa', 'Performance/Sports Drinks'),
    ('Fuel Eyewear', 'Eyewear'),
    ('Fuel Eyewear', 'Technical sports Apparel'),
    ('Grupo DASA', 'Insurance'),
    ('Yoppi', 'Eyewear'),
    ('Puro Verde', 'Performance/Sports Drinks'),
    ('Oakberry', 'Performance/Sports Drinks'),
    ('Italac', 'Performance/Sports Drinks'),
    ('Caffeine Army', 'Performance/Sports Drinks'),
    ('Kaillash', 'Technical sports Apparel'),
    ('Juçaí', 'Performance/Sports Drinks'),
    ('Grupo Zanlorenzi (Campo Largo)', 'Performance/Sports Drinks'),
    ('PepsiCo', 'Performance/Sports Drinks'),
    ('Itaú', 'Financial services'),
    ('Bradesco Seguros', 'Insurance'),
    ('Tirolez', 'Performance/Sports Drinks'),
    ('Mondelēz International', 'Performance/Sports Drinks')
  ) AS t(empresa_name, sector_name)
  GROUP BY empresa_name
),
sector_ids_resolved AS (
  SELECT 
    esm.empresa_name,
    COALESCE(
      (SELECT array_agg(s.id ORDER BY s.name)
       FROM unnest(esm.sector_names) AS sector_name_text
       INNER JOIN sectors s ON s.name = sector_name_text),
      ARRAY[]::UUID[]
    ) AS sector_ids
  FROM empresa_sectors_map esm
)
UPDATE organizations o
SET sector_ids = COALESCE(sir.sector_ids, ARRAY[]::UUID[])
FROM sector_ids_resolved sir
WHERE LOWER(TRIM(o.name)) = LOWER(TRIM(sir.empresa_name));