-- Migração 009: Atualizar sponsorship_counterparts com explicações completas do PDF UTMB 2025
-- Remove os registros antigos e reinsere com textos completos baseados no PDF

-- Deletar todos os sponsorship_counterparts existentes
DELETE FROM sponsorship_counterparts;

-- Inserir contra-partidas completas para Title (R$ 1.5 MM)
DO $$
DECLARE
  title_tier_id UUID;
BEGIN
  SELECT id INTO title_tier_id FROM sponsorship_tiers WHERE name = 'Title' AND value_brl = 1500000.00 LIMIT 1;
  
  INSERT INTO sponsorship_counterparts (tier_id, name, included, details) VALUES
    (title_tier_id, 'Nome da prova/Camiseta', TRUE, 'Ao adquirir os Naming Rights, sua marca não só encabeça o Paraty Brazil by UTMB, mas também se integra a cada ponto de contato com o evento. Isso oferece uma exposição ímpar, com uma visibilidade acima de qualquer outra cota de patrocínio. Incluem ativações, experiências e vivências.'),
    (title_tier_id, 'Gift Finisher', TRUE, 'Os Gifts Finisher são os prêmios aguardados por quem completa a corrida, marcando sua conquista no Paraty Brazil by UTMB. Associar sua marca a esses prêmios significa estar presente no auge da realização dos atletas, estabelecendo uma ligação emocional profunda e uma recordação positiva duradoura da sua contribuição à sua vitória. *até 30 de junho'),
    (title_tier_id, 'Kit do Atleta', TRUE, 'Conjunto de itens essenciais para a corrida. Incluindo seus produtos no Kit do Atleta, você cria pontos de contato diretos com participantes, transformando cada item em uma oportunidade de engajamento. Esta estratégia não só enriquece a experiência do atleta com sua marca, mas também amplia seu alcance, solidificando sua presença na memória dos corredores como um suporte vital em sua jornada.'),
    (title_tier_id, 'Champions Zone', TRUE, 'A área de entrevistas para os atletas campeões no Paraty Brazil by UTMB é o palco onde os momentos de triunfo são compartilhados com o mundo. Patrocinar este espaço oferece à sua marca visibilidade exclusiva durante os entrevistas pós-corrida, onde os vencedores expressam suas emoções e conquistas.'),
    (title_tier_id, 'VIP Experience', TRUE, 'A Área VIP e VIP Experience oferecem um espaço exclusivo para sua marca criar experiências únicas para seus clientes no Paraty Brazil by UTMB. Este é o cenário ideal para impressionar, com acesso privilegiado e vistas inigualáveis, ao tratamento especial, ampliando seu impacto e deixando uma impressão duradoura de excelência e exclusividade.'),
    (title_tier_id, 'Anúncio speaker', TRUE, 'Ter sua marca anunciada pelos locutores nas corridas do Paraty Brazil by UTMB amplifica sua presença, garantindo que sua mensagem ecoe durante momentos críticos de emoção e expectativa. Esta estratégia coloca sua marca no epicentro da ação, associando-a verbalmente aos picos de entusiasmo, alcançando atletas e espectadores de forma direta e memorável.'),
    (title_tier_id, 'Guia do Atleta', TRUE, 'Colocar sua marca nas páginas da revista digital essencial do Paraty Brazil by UTMB, que detalha todas as informações do evento. É uma oportunidade de estar em constante contato com os atletas, oferecendo-lhes orientação e apoio, e associando sua marca à confiabilidade e ao valor informativo indispensável para a sua preparação e sucesso.'),
    (title_tier_id, 'Backdrop Finisher', TRUE, 'O Backdrop Finisher é o pano de fundo para as fotos de celebração dos atletas que concluem o Paraty Brazil by UTMB, oferecendo uma visibilidade sem precedentes para sua marca. Situado na linha de chegada, este espaço captura momentos de triunfo e emoção, garantindo que sua marca seja parte integrante dessas memórias significativas e amplamente compartilhadas.'),
    (title_tier_id, 'Backdrop', TRUE, 'O backdrop, cenário das fotos mais desejadas e compartilhadas pelos atletas no Paraty Brazil by UTMB, oferece uma visibilidade incomparável à sua marca. Associando-se a momentos de alegria e celebração, sua marca se torna parte integral dos memórias e conquistas dos participantes, garantindo um destaque emocional e visual duradouro em suas histórias.'),
    (title_tier_id, 'Pórtico de Largada/Chegada', TRUE, 'Patrocinar o Pórtico de Largada e Chegada no Paraty Brazil by UTMB posiciona sua marca nos momentos mais emblemáticos do evento. Este ponto focal, onde emoções transbordam ao iniciar e concluir a corrida, oferece uma visibilidade sem igual, associando sua marca ao início de desafios e à celebração de conquistas, criando memórias inesquecíveis.'),
    (title_tier_id, 'Capa de Gradil', TRUE, 'As paredes do corredor de largada e chegada, posiciona sua marca no coração do Paraty Brazil by UTMB. Esse ponto estratégico assegura máxima exposição, vinculando sua imagem aos momentos de largada e chegada dos atletas, quando eles iniciam e realizam essa jornada extraordinária.'),
    (title_tier_id, 'Logo/Link Site Oficial', TRUE, 'Inserir seu logo no site do Paraty Brazil by UTMB coloca sua marca em um ponto de interação digital constante com atletas, seguidores e interessados. Esta presença online não só aumenta o reconhecimento da marca, mas também associa sua imagem ao prestígio e à aventura que o evento representa, gerando engajamento e conexão direta com uma comunidade global.'),
    (title_tier_id, 'Windflag', TRUE, 'Os Windflags no Paraty Brazil by UTMB são bandeiras estilizadas que oferecem uma exposição contínua da sua marca ao longo do percurso, capturando a atenção de atletas, espectadores e mídias. Sua presença em pontos estratégicos garante que sua marca seja vista em momentos de determinação e triunfo, associando-a à energia vibrante e ao espírito dinâmico do evento.'),
    (title_tier_id, 'Naming . Posto de Controle (PC)', TRUE, 'Os Naming Rights dos Postos de Controle permitem que sua marca nomeie e ative espaços cruciais de abastecimento para os atletas no Paraty Brazil by UTMB. Isso significa presença constante onde o suporte é mais necessário, vinculando sua marca à energia e ao alívio em momentos de desafio, e criando uma associação positiva de cuidado e apoio na mente dos participantes.'),
    (title_tier_id, 'Estande Expo', TRUE, 'A principal feira do mercado outdoor do Paraty Brazil by UTMB é sua vitrine para destacar produtos e inovações o um público apaixonado e especializado. Participar ativamente neste espaço não apenas aumenta a visibilidade da sua marca, mas também a posiciona como referência no setor, aproveitando a oportunidade de interagir diretamente com entusiastas, atletas e parceiros.'),
    (title_tier_id, 'Social Mídia/E-mail MKT', TRUE, 'Ao integrar sua marca às campanhas de Social Media e Mail Marketing do Paraty Brazil by UTMB, você alcança diretamente um público engajado e interessado, ampliando seu alcance e fortalecendo sua presença online. Esta parceria estratégica não só eleva a visibilidade da sua marca, mas também permite comunicações personalizadas que ressoam com a comunidade, cultivando uma relação mais próxima e significativa com os entusiastas do evento.'),
    (title_tier_id, 'Assets Vídeos de Fotos', TRUE, 'Sua marca ganha acesso a um rico acervo de conteúdo visual exclusivo do evento. Esta vantagem permite que você utilize imagens impactantes e momentos emocionantes em suas próprias publicações, reforçando a associação da sua marca com as aventuras e histórias inspiradoras do evento, enriquecendo sua comunicação e engajando seu público de maneira autêntica e vibrante.'),
    (title_tier_id, 'Cortesia', TRUE, 'Oferecer inscrições cortesias do Paraty Brazil by UTMB é uma forma elegante de engajar sua equipe, clientes ou parceiros, proporcionando-lhes uma experiência inesquecível. Este gesto de generosidade não só fortalece relacionamentos, mas também associa sua marca aos valores de superação e aventura do evento, incentivando o espírito de equipe e o paixão pelo esporte ao vivo, enraizando sua marca na memória coletiva dos participantes.'),
    (title_tier_id, 'Talk Expo', TRUE, 'Promover um talk na Expo do Paraty Brazil by UTMB posiciona sua marca como uma voz de autoridade e inovação no universo outdoor. Este plataforma de palestras oferece uma oportunidade ímpar de se conectar diretamente com um público apaixonado, compartilhando conhecimentos, experiências e valores que ressoam com a comunidade. Além de reforçar o posicionamento da sua marca, estimula o diálogo, a educação e a construção de uma relação mais profunda e significativa com os atletas e entusiastas.'),
    (title_tier_id, 'Vídeo Telão', TRUE, 'Utilizar os telões do evento para exibir vídeos promocionais da sua marca é uma estratégia poderosa de ativação no Paraty Brazil by UTMB. Esta exposição em grande escala garante que sua mensagem alcance atletas, espectadores e participantes, criando um impacto visual memorável. É uma chance única de destacar sua marca, produtos ou iniciativas, engajando a audiência em tempo real e ampliando significativamente sua visibilidade durante momentos chave do evento.'),
    (title_tier_id, 'After Movie', TRUE, 'O After Movie do Paraty Brazil by UTMB eterniza sua marca nos melhores momentos desta edição épica. Este vídeo, uma cápsula do tempo de triunfos e emoções, será compartilhado e revisto por uma audiência global, garantindo que sua marca seja lembrada não apenas como patrocinadora, mas como parte integral da história e do legado do evento.'),
    (title_tier_id, 'Permuta', TRUE, 'A permuta oferece uma oportunidade estratégica para sua marca se envolver no Paraty Brazil by UTMB, permitindo o abatimento do valor de patrocínio mediante o fornecimento de produtos ou serviços. Esta abordagem enriquece a experiência dos participantes, destacando sua marca como um colaborador vital que contribui para o sucesso e a qualidade do evento.');
END $$;

-- Inserir contra-partidas completas para Partner (R$ 400 Mil)
DO $$
DECLARE
  partner_tier_id UUID;
BEGIN
  SELECT id INTO partner_tier_id FROM sponsorship_tiers WHERE name = 'Partner' AND value_brl = 400000.00 LIMIT 1;
  
  INSERT INTO sponsorship_counterparts (tier_id, name, included, details) VALUES
    (partner_tier_id, 'Pórtico de Largada/Chegada', TRUE, 'Patrocinar o Pórtico de Largada e Chegada no Paraty Brazil by UTMB posiciona sua marca nos momentos mais emblemáticos do evento. Este ponto focal, onde emoções transbordam ao iniciar e concluir a corrida, oferece uma visibilidade sem igual, associando sua marca ao início de desafios e à celebração de conquistas, criando memórias inesquecíveis.'),
    (partner_tier_id, 'Champions Zone', TRUE, 'A área de entrevistas para os atletas campeões no Paraty Brazil by UTMB é o palco onde os momentos de triunfo são compartilhados com o mundo. Patrocinar este espaço oferece à sua marca visibilidade exclusiva durante os entrevistas pós-corrida, onde os vencedores expressam suas emoções e conquistas.'),
    (partner_tier_id, 'Capa de Gradil', TRUE, 'As paredes do corredor de largada e chegada, posiciona sua marca no coração do Paraty Brazil by UTMB. Esse ponto estratégico assegura máxima exposição, vinculando sua imagem aos momentos de largada e chegada dos atletas, quando eles iniciam e realizam essa jornada extraordinária.'),
    (partner_tier_id, 'VIP Experience', TRUE, 'A Área VIP e VIP Experience oferecem um espaço exclusivo para sua marca criar experiências únicas para seus clientes no Paraty Brazil by UTMB. Este é o cenário ideal para impressionar, com acesso privilegiado e vistas inigualáveis, ao tratamento especial, ampliando seu impacto e deixando uma impressão duradoura de excelência e exclusividade.'),
    (partner_tier_id, 'Backdrop Finisher', TRUE, 'O Backdrop Finisher é o pano de fundo para as fotos de celebração dos atletas que concluem o Paraty Brazil by UTMB, oferecendo uma visibilidade sem precedentes para sua marca. Situado na linha de chegada, este espaço captura momentos de triunfo e emoção, garantindo que sua marca seja parte integrante dessas memórias significativas e amplamente compartilhadas.'),
    (partner_tier_id, 'Windflag', TRUE, 'Os Windflags no Paraty Brazil by UTMB são bandeiras estilizadas que oferecem uma exposição contínua da sua marca ao longo do percurso, capturando a atenção de atletas, espectadores e mídias. Sua presença em pontos estratégicos garante que sua marca seja vista em momentos de determinação e triunfo, associando-a à energia vibrante e ao espírito dinâmico do evento.'),
    (partner_tier_id, 'Guia do Atleta', TRUE, 'Colocar sua marca nas páginas da revista digital essencial do Paraty Brazil by UTMB, que detalha todas as informações do evento. É uma oportunidade de estar em constante contato com os atletas, oferecendo-lhes orientação e apoio, e associando sua marca à confiabilidade e ao valor informativo indispensável para a sua preparação e sucesso.'),
    (partner_tier_id, 'Logo/Link Site Oficial', TRUE, 'Inserir seu logo no site do Paraty Brazil by UTMB coloca sua marca em um ponto de interação digital constante com atletas, seguidores e interessados. Esta presença online não só aumenta o reconhecimento da marca, mas também associa sua imagem ao prestígio e à aventura que o evento representa, gerando engajamento e conexão direta com uma comunidade global.'),
    (partner_tier_id, 'Kit do Atleta', TRUE, 'Conjunto de itens essenciais para a corrida. Incluindo seus produtos no Kit do Atleta, você cria pontos de contato diretos com participantes, transformando cada item em uma oportunidade de engajamento. Esta estratégia não só enriquece a experiência do atleta com sua marca, mas também amplia seu alcance, solidificando sua presença na memória dos corredores como um suporte vital em sua jornada.'),
    (partner_tier_id, 'Backdrop', TRUE, 'O backdrop, cenário das fotos mais desejadas e compartilhadas pelos atletas no Paraty Brazil by UTMB, oferece uma visibilidade incomparável à sua marca. Associando-se a momentos de alegria e celebração, sua marca se torna parte integral dos memórias e conquistas dos participantes, garantindo um destaque emocional e visual duradouro em suas histórias.'),
    (partner_tier_id, 'Anúncio speaker', TRUE, 'Ter sua marca anunciada pelos locutores nas corridas do Paraty Brazil by UTMB amplifica sua presença, garantindo que sua mensagem ecoe durante momentos críticos de emoção e expectativa. Esta estratégia coloca sua marca no epicentro da ação, associando-a verbalmente aos picos de entusiasmo, alcançando atletas e espectadores de forma direta e memorável.'),
    (partner_tier_id, 'Naming . Posto de Controle (PC)', TRUE, 'Os Naming Rights dos Postos de Controle permitem que sua marca nomeie e ative espaços cruciais de abastecimento para os atletas no Paraty Brazil by UTMB. Isso significa presença constante onde o suporte é mais necessário, vinculando sua marca à energia e ao alívio em momentos de desafio, e criando uma associação positiva de cuidado e apoio na mente dos participantes.'),
    (partner_tier_id, 'Estande Expo', TRUE, 'A principal feira do mercado outdoor do Paraty Brazil by UTMB é sua vitrine para destacar produtos e inovações o um público apaixonado e especializado. Participar ativamente neste espaço não apenas aumenta a visibilidade da sua marca, mas também a posiciona como referência no setor, aproveitando a oportunidade de interagir diretamente com entusiastas, atletas e parceiros.'),
    (partner_tier_id, 'Social Mídia/E-mail MKT', TRUE, 'Ao integrar sua marca às campanhas de Social Media e Mail Marketing do Paraty Brazil by UTMB, você alcança diretamente um público engajado e interessado, ampliando seu alcance e fortalecendo sua presença online. Esta parceria estratégica não só eleva a visibilidade da sua marca, mas também permite comunicações personalizadas que ressoam com a comunidade, cultivando uma relação mais próxima e significativa com os entusiastas do evento.'),
    (partner_tier_id, 'Assets Vídeos de Fotos', TRUE, 'Sua marca ganha acesso a um rico acervo de conteúdo visual exclusivo do evento. Esta vantagem permite que você utilize imagens impactantes e momentos emocionantes em suas próprias publicações, reforçando a associação da sua marca com as aventuras e histórias inspiradoras do evento, enriquecendo sua comunicação e engajando seu público de maneira autêntica e vibrante.'),
    (partner_tier_id, 'Cortesia', TRUE, 'Oferecer inscrições cortesias do Paraty Brazil by UTMB é uma forma elegante de engajar sua equipe, clientes ou parceiros, proporcionando-lhes uma experiência inesquecível. Este gesto de generosidade não só fortalece relacionamentos, mas também associa sua marca aos valores de superação e aventura do evento, incentivando o espírito de equipe e o paixão pelo esporte ao vivo, enraizando sua marca na memória coletiva dos participantes.'),
    (partner_tier_id, 'Talk Expo', TRUE, 'Promover um talk na Expo do Paraty Brazil by UTMB posiciona sua marca como uma voz de autoridade e inovação no universo outdoor. Este plataforma de palestras oferece uma oportunidade ímpar de se conectar diretamente com um público apaixonado, compartilhando conhecimentos, experiências e valores que ressoam com a comunidade. Além de reforçar o posicionamento da sua marca, estimula o diálogo, a educação e a construção de uma relação mais profunda e significativa com os atletas e entusiastas.'),
    (partner_tier_id, 'Vídeo Telão', TRUE, 'Utilizar os telões do evento para exibir vídeos promocionais da sua marca é uma estratégia poderosa de ativação no Paraty Brazil by UTMB. Esta exposição em grande escala garante que sua mensagem alcance atletas, espectadores e participantes, criando um impacto visual memorável. É uma chance única de destacar sua marca, produtos ou iniciativas, engajando a audiência em tempo real e ampliando significativamente sua visibilidade durante momentos chave do evento.'),
    (partner_tier_id, 'After Movie', TRUE, 'O After Movie do Paraty Brazil by UTMB eterniza sua marca nos melhores momentos desta edição épica. Este vídeo, uma cápsula do tempo de triunfos e emoções, será compartilhado e revisto por uma audiência global, garantindo que sua marca seja lembrada não apenas como patrocinadora, mas como parte integral da história e do legado do evento.'),
    (partner_tier_id, 'Permuta', TRUE, 'A permuta oferece uma oportunidade estratégica para sua marca se envolver no Paraty Brazil by UTMB, permitindo o abatimento do valor de patrocínio mediante o fornecimento de produtos ou serviços. Esta abordagem enriquece a experiência dos participantes, destacando sua marca como um colaborador vital que contribui para o sucesso e a qualidade do evento.');
END $$;

-- Inserir contra-partidas completas para Supplier R$ 130 Mil
DO $$
DECLARE
  supplier_130_id UUID;
BEGIN
  SELECT id INTO supplier_130_id FROM sponsorship_tiers WHERE name = 'Supplier' AND value_brl = 130000.00 LIMIT 1;
  
  INSERT INTO sponsorship_counterparts (tier_id, name, included, details) VALUES
    (supplier_130_id, 'Capa de Gradil', TRUE, 'As paredes do corredor de largada e chegada, posiciona sua marca no coração do Paraty Brazil by UTMB. Esse ponto estratégico assegura máxima exposição, vinculando sua imagem aos momentos de largada e chegada dos atletas, quando eles iniciam e realizam essa jornada extraordinária.'),
    (supplier_130_id, 'VIP Experience', TRUE, 'A Área VIP e VIP Experience oferecem um espaço exclusivo para sua marca criar experiências únicas para seus clientes no Paraty Brazil by UTMB. Este é o cenário ideal para impressionar, com acesso privilegiado e vistas inigualáveis, ao tratamento especial, ampliando seu impacto e deixando uma impressão duradoura de excelência e exclusividade.'),
    (supplier_130_id, 'Backdrop Finisher', TRUE, 'O Backdrop Finisher é o pano de fundo para as fotos de celebração dos atletas que concluem o Paraty Brazil by UTMB, oferecendo uma visibilidade sem precedentes para sua marca. Situado na linha de chegada, este espaço captura momentos de triunfo e emoção, garantindo que sua marca seja parte integrante dessas memórias significativas e amplamente compartilhadas.'),
    (supplier_130_id, 'Windflag', TRUE, 'Os Windflags no Paraty Brazil by UTMB são bandeiras estilizadas que oferecem uma exposição contínua da sua marca ao longo do percurso, capturando a atenção de atletas, espectadores e mídias. Sua presença em pontos estratégicos garante que sua marca seja vista em momentos de determinação e triunfo, associando-a à energia vibrante e ao espírito dinâmico do evento.'),
    (supplier_130_id, 'Guia do Atleta', TRUE, 'Colocar sua marca nas páginas da revista digital essencial do Paraty Brazil by UTMB, que detalha todas as informações do evento. É uma oportunidade de estar em constante contato com os atletas, oferecendo-lhes orientação e apoio, e associando sua marca à confiabilidade e ao valor informativo indispensável para a sua preparação e sucesso.'),
    (supplier_130_id, 'Logo/Link Site Oficial', TRUE, 'Inserir seu logo no site do Paraty Brazil by UTMB coloca sua marca em um ponto de interação digital constante com atletas, seguidores e interessados. Esta presença online não só aumenta o reconhecimento da marca, mas também associa sua imagem ao prestígio e à aventura que o evento representa, gerando engajamento e conexão direta com uma comunidade global.'),
    (supplier_130_id, 'Kit do Atleta', TRUE, 'Conjunto de itens essenciais para a corrida. Incluindo seus produtos no Kit do Atleta, você cria pontos de contato diretos com participantes, transformando cada item em uma oportunidade de engajamento. Esta estratégia não só enriquece a experiência do atleta com sua marca, mas também amplia seu alcance, solidificando sua presença na memória dos corredores como um suporte vital em sua jornada.'),
    (supplier_130_id, 'Backdrop', TRUE, 'O backdrop, cenário das fotos mais desejadas e compartilhadas pelos atletas no Paraty Brazil by UTMB, oferece uma visibilidade incomparável à sua marca. Associando-se a momentos de alegria e celebração, sua marca se torna parte integral dos memórias e conquistas dos participantes, garantindo um destaque emocional e visual duradouro em suas histórias.'),
    (supplier_130_id, 'Anúncio speaker', TRUE, 'Ter sua marca anunciada pelos locutores nas corridas do Paraty Brazil by UTMB amplifica sua presença, garantindo que sua mensagem ecoe durante momentos críticos de emoção e expectativa. Esta estratégia coloca sua marca no epicentro da ação, associando-a verbalmente aos picos de entusiasmo, alcançando atletas e espectadores de forma direta e memorável.'),
    (supplier_130_id, 'Naming . Posto de Controle (PC)', TRUE, 'Os Naming Rights dos Postos de Controle permitem que sua marca nomeie e ative espaços cruciais de abastecimento para os atletas no Paraty Brazil by UTMB. Isso significa presença constante onde o suporte é mais necessário, vinculando sua marca à energia e ao alívio em momentos de desafio, e criando uma associação positiva de cuidado e apoio na mente dos participantes.'),
    (supplier_130_id, 'Estande Expo', TRUE, 'A principal feira do mercado outdoor do Paraty Brazil by UTMB é sua vitrine para destacar produtos e inovações o um público apaixonado e especializado. Participar ativamente neste espaço não apenas aumenta a visibilidade da sua marca, mas também a posiciona como referência no setor, aproveitando a oportunidade de interagir diretamente com entusiastas, atletas e parceiros.'),
    (supplier_130_id, 'Social Mídia/E-mail MKT', TRUE, 'Ao integrar sua marca às campanhas de Social Media e Mail Marketing do Paraty Brazil by UTMB, você alcança diretamente um público engajado e interessado, ampliando seu alcance e fortalecendo sua presença online. Esta parceria estratégica não só eleva a visibilidade da sua marca, mas também permite comunicações personalizadas que ressoam com a comunidade, cultivando uma relação mais próxima e significativa com os entusiastas do evento.'),
    (supplier_130_id, 'Assets Vídeos de Fotos', TRUE, 'Sua marca ganha acesso a um rico acervo de conteúdo visual exclusivo do evento. Esta vantagem permite que você utilize imagens impactantes e momentos emocionantes em suas próprias publicações, reforçando a associação da sua marca com as aventuras e histórias inspiradoras do evento, enriquecendo sua comunicação e engajando seu público de maneira autêntica e vibrante.'),
    (supplier_130_id, 'Cortesia', TRUE, 'Oferecer inscrições cortesias do Paraty Brazil by UTMB é uma forma elegante de engajar sua equipe, clientes ou parceiros, proporcionando-lhes uma experiência inesquecível. Este gesto de generosidade não só fortalece relacionamentos, mas também associa sua marca aos valores de superação e aventura do evento, incentivando o espírito de equipe e o paixão pelo esporte ao vivo, enraizando sua marca na memória coletiva dos participantes.'),
    (supplier_130_id, 'Talk Expo', TRUE, 'Promover um talk na Expo do Paraty Brazil by UTMB posiciona sua marca como uma voz de autoridade e inovação no universo outdoor. Este plataforma de palestras oferece uma oportunidade ímpar de se conectar diretamente com um público apaixonado, compartilhando conhecimentos, experiências e valores que ressoam com a comunidade. Além de reforçar o posicionamento da sua marca, estimula o diálogo, a educação e a construção de uma relação mais profunda e significativa com os atletas e entusiastas.'),
    (supplier_130_id, 'Vídeo Telão', TRUE, 'Utilizar os telões do evento para exibir vídeos promocionais da sua marca é uma estratégia poderosa de ativação no Paraty Brazil by UTMB. Esta exposição em grande escala garante que sua mensagem alcance atletas, espectadores e participantes, criando um impacto visual memorável. É uma chance única de destacar sua marca, produtos ou iniciativas, engajando a audiência em tempo real e ampliando significativamente sua visibilidade durante momentos chave do evento.'),
    (supplier_130_id, 'After Movie', TRUE, 'O After Movie do Paraty Brazil by UTMB eterniza sua marca nos melhores momentos desta edição épica. Este vídeo, uma cápsula do tempo de triunfos e emoções, será compartilhado e revisto por uma audiência global, garantindo que sua marca seja lembrada não apenas como patrocinadora, mas como parte integral da história e do legado do evento.'),
    (supplier_130_id, 'Permuta', TRUE, 'A permuta oferece uma oportunidade estratégica para sua marca se envolver no Paraty Brazil by UTMB, permitindo o abatimento do valor de patrocínio mediante o fornecimento de produtos ou serviços. Esta abordagem enriquece a experiência dos participantes, destacando sua marca como um colaborador vital que contribui para o sucesso e a qualidade do evento.');
END $$;

-- Inserir contra-partidas completas para Supplier R$ 90 Mil
DO $$
DECLARE
  supplier_90_id UUID;
BEGIN
  SELECT id INTO supplier_90_id FROM sponsorship_tiers WHERE name = 'Supplier' AND value_brl = 90000.00 LIMIT 1;
  
  INSERT INTO sponsorship_counterparts (tier_id, name, included, details) VALUES
    (supplier_90_id, 'Guia do Atleta', TRUE, 'Colocar sua marca nas páginas da revista digital essencial do Paraty Brazil by UTMB, que detalha todas as informações do evento. É uma oportunidade de estar em constante contato com os atletas, oferecendo-lhes orientação e apoio, e associando sua marca à confiabilidade e ao valor informativo indispensável para a sua preparação e sucesso.'),
    (supplier_90_id, 'Logo/Link Site Oficial', TRUE, 'Inserir seu logo no site do Paraty Brazil by UTMB coloca sua marca em um ponto de interação digital constante com atletas, seguidores e interessados. Esta presença online não só aumenta o reconhecimento da marca, mas também associa sua imagem ao prestígio e à aventura que o evento representa, gerando engajamento e conexão direta com uma comunidade global.'),
    (supplier_90_id, 'Kit do Atleta', TRUE, 'Conjunto de itens essenciais para a corrida. Incluindo seus produtos no Kit do Atleta, você cria pontos de contato diretos com participantes, transformando cada item em uma oportunidade de engajamento. Esta estratégia não só enriquece a experiência do atleta com sua marca, mas também amplia seu alcance, solidificando sua presença na memória dos corredores como um suporte vital em sua jornada.'),
    (supplier_90_id, 'Backdrop', TRUE, 'O backdrop, cenário das fotos mais desejadas e compartilhadas pelos atletas no Paraty Brazil by UTMB, oferece uma visibilidade incomparável à sua marca. Associando-se a momentos de alegria e celebração, sua marca se torna parte integral dos memórias e conquistas dos participantes, garantindo um destaque emocional e visual duradouro em suas histórias.'),
    (supplier_90_id, 'Anúncio speaker', TRUE, 'Ter sua marca anunciada pelos locutores nas corridas do Paraty Brazil by UTMB amplifica sua presença, garantindo que sua mensagem ecoe durante momentos críticos de emoção e expectativa. Esta estratégia coloca sua marca no epicentro da ação, associando-a verbalmente aos picos de entusiasmo, alcançando atletas e espectadores de forma direta e memorável.'),
    (supplier_90_id, 'Naming . Posto de Controle (PC)', TRUE, 'Os Naming Rights dos Postos de Controle permitem que sua marca nomeie e ative espaços cruciais de abastecimento para os atletas no Paraty Brazil by UTMB. Isso significa presença constante onde o suporte é mais necessário, vinculando sua marca à energia e ao alívio em momentos de desafio, e criando uma associação positiva de cuidado e apoio na mente dos participantes.'),
    (supplier_90_id, 'Estande Expo', TRUE, 'A principal feira do mercado outdoor do Paraty Brazil by UTMB é sua vitrine para destacar produtos e inovações o um público apaixonado e especializado. Participar ativamente neste espaço não apenas aumenta a visibilidade da sua marca, mas também a posiciona como referência no setor, aproveitando a oportunidade de interagir diretamente com entusiastas, atletas e parceiros.'),
    (supplier_90_id, 'Social Mídia/E-mail MKT', TRUE, 'Ao integrar sua marca às campanhas de Social Media e Mail Marketing do Paraty Brazil by UTMB, você alcança diretamente um público engajado e interessado, ampliando seu alcance e fortalecendo sua presença online. Esta parceria estratégica não só eleva a visibilidade da sua marca, mas também permite comunicações personalizadas que ressoam com a comunidade, cultivando uma relação mais próxima e significativa com os entusiastas do evento.'),
    (supplier_90_id, 'Assets Vídeos de Fotos', TRUE, 'Sua marca ganha acesso a um rico acervo de conteúdo visual exclusivo do evento. Esta vantagem permite que você utilize imagens impactantes e momentos emocionantes em suas próprias publicações, reforçando a associação da sua marca com as aventuras e histórias inspiradoras do evento, enriquecendo sua comunicação e engajando seu público de maneira autêntica e vibrante.'),
    (supplier_90_id, 'Cortesia', TRUE, 'Oferecer inscrições cortesias do Paraty Brazil by UTMB é uma forma elegante de engajar sua equipe, clientes ou parceiros, proporcionando-lhes uma experiência inesquecível. Este gesto de generosidade não só fortalece relacionamentos, mas também associa sua marca aos valores de superação e aventura do evento, incentivando o espírito de equipe e o paixão pelo esporte ao vivo, enraizando sua marca na memória coletiva dos participantes.'),
    (supplier_90_id, 'Talk Expo', TRUE, 'Promover um talk na Expo do Paraty Brazil by UTMB posiciona sua marca como uma voz de autoridade e inovação no universo outdoor. Este plataforma de palestras oferece uma oportunidade ímpar de se conectar diretamente com um público apaixonado, compartilhando conhecimentos, experiências e valores que ressoam com a comunidade. Além de reforçar o posicionamento da sua marca, estimula o diálogo, a educação e a construção de uma relação mais profunda e significativa com os atletas e entusiastas.'),
    (supplier_90_id, 'Vídeo Telão', TRUE, 'Utilizar os telões do evento para exibir vídeos promocionais da sua marca é uma estratégia poderosa de ativação no Paraty Brazil by UTMB. Esta exposição em grande escala garante que sua mensagem alcance atletas, espectadores e participantes, criando um impacto visual memorável. É uma chance única de destacar sua marca, produtos ou iniciativas, engajando a audiência em tempo real e ampliando significativamente sua visibilidade durante momentos chave do evento.'),
    (supplier_90_id, 'After Movie', TRUE, 'O After Movie do Paraty Brazil by UTMB eterniza sua marca nos melhores momentos desta edição épica. Este vídeo, uma cápsula do tempo de triunfos e emoções, será compartilhado e revisto por uma audiência global, garantindo que sua marca seja lembrada não apenas como patrocinadora, mas como parte integral da história e do legado do evento.'),
    (supplier_90_id, 'Permuta', TRUE, 'A permuta oferece uma oportunidade estratégica para sua marca se envolver no Paraty Brazil by UTMB, permitindo o abatimento do valor de patrocínio mediante o fornecimento de produtos ou serviços. Esta abordagem enriquece a experiência dos participantes, destacando sua marca como um colaborador vital que contribui para o sucesso e a qualidade do evento.');
END $$;

-- Inserir contra-partidas completas para Supplier R$ 60 Mil
DO $$
DECLARE
  supplier_60_id UUID;
BEGIN
  SELECT id INTO supplier_60_id FROM sponsorship_tiers WHERE name = 'Supplier' AND value_brl = 60000.00 LIMIT 1;
  
  INSERT INTO sponsorship_counterparts (tier_id, name, included, details) VALUES
    (supplier_60_id, 'Guia do Atleta', TRUE, 'Colocar sua marca nas páginas da revista digital essencial do Paraty Brazil by UTMB, que detalha todas as informações do evento. É uma oportunidade de estar em constante contato com os atletas, oferecendo-lhes orientação e apoio, e associando sua marca à confiabilidade e ao valor informativo indispensável para a sua preparação e sucesso.'),
    (supplier_60_id, 'Logo/Link Site Oficial', TRUE, 'Inserir seu logo no site do Paraty Brazil by UTMB coloca sua marca em um ponto de interação digital constante com atletas, seguidores e interessados. Esta presença online não só aumenta o reconhecimento da marca, mas também associa sua imagem ao prestígio e à aventura que o evento representa, gerando engajamento e conexão direta com uma comunidade global.'),
    (supplier_60_id, 'Kit do Atleta', TRUE, 'Conjunto de itens essenciais para a corrida. Incluindo seus produtos no Kit do Atleta, você cria pontos de contato diretos com participantes, transformando cada item em uma oportunidade de engajamento. Esta estratégia não só enriquece a experiência do atleta com sua marca, mas também amplia seu alcance, solidificando sua presença na memória dos corredores como um suporte vital em sua jornada.'),
    (supplier_60_id, 'Backdrop', TRUE, 'O backdrop, cenário das fotos mais desejadas e compartilhadas pelos atletas no Paraty Brazil by UTMB, oferece uma visibilidade incomparável à sua marca. Associando-se a momentos de alegria e celebração, sua marca se torna parte integral dos memórias e conquistas dos participantes, garantindo um destaque emocional e visual duradouro em suas histórias.'),
    (supplier_60_id, 'Anúncio speaker', TRUE, 'Ter sua marca anunciada pelos locutores nas corridas do Paraty Brazil by UTMB amplifica sua presença, garantindo que sua mensagem ecoe durante momentos críticos de emoção e expectativa. Esta estratégia coloca sua marca no epicentro da ação, associando-a verbalmente aos picos de entusiasmo, alcançando atletas e espectadores de forma direta e memorável.'),
    (supplier_60_id, 'Naming . Posto de Controle (PC)', TRUE, 'Os Naming Rights dos Postos de Controle permitem que sua marca nomeie e ative espaços cruciais de abastecimento para os atletas no Paraty Brazil by UTMB. Isso significa presença constante onde o suporte é mais necessário, vinculando sua marca à energia e ao alívio em momentos de desafio, e criando uma associação positiva de cuidado e apoio na mente dos participantes.'),
    (supplier_60_id, 'Estande Expo', TRUE, 'A principal feira do mercado outdoor do Paraty Brazil by UTMB é sua vitrine para destacar produtos e inovações o um público apaixonado e especializado. Participar ativamente neste espaço não apenas aumenta a visibilidade da sua marca, mas também a posiciona como referência no setor, aproveitando a oportunidade de interagir diretamente com entusiastas, atletas e parceiros.'),
    (supplier_60_id, 'Social Mídia/E-mail MKT', TRUE, 'Ao integrar sua marca às campanhas de Social Media e Mail Marketing do Paraty Brazil by UTMB, você alcança diretamente um público engajado e interessado, ampliando seu alcance e fortalecendo sua presença online. Esta parceria estratégica não só eleva a visibilidade da sua marca, mas também permite comunicações personalizadas que ressoam com a comunidade, cultivando uma relação mais próxima e significativa com os entusiastas do evento.'),
    (supplier_60_id, 'Assets Vídeos de Fotos', TRUE, 'Sua marca ganha acesso a um rico acervo de conteúdo visual exclusivo do evento. Esta vantagem permite que você utilize imagens impactantes e momentos emocionantes em suas próprias publicações, reforçando a associação da sua marca com as aventuras e histórias inspiradoras do evento, enriquecendo sua comunicação e engajando seu público de maneira autêntica e vibrante.'),
    (supplier_60_id, 'Cortesia', TRUE, 'Oferecer inscrições cortesias do Paraty Brazil by UTMB é uma forma elegante de engajar sua equipe, clientes ou parceiros, proporcionando-lhes uma experiência inesquecível. Este gesto de generosidade não só fortalece relacionamentos, mas também associa sua marca aos valores de superação e aventura do evento, incentivando o espírito de equipe e o paixão pelo esporte ao vivo, enraizando sua marca na memória coletiva dos participantes.'),
    (supplier_60_id, 'Talk Expo', TRUE, 'Promover um talk na Expo do Paraty Brazil by UTMB posiciona sua marca como uma voz de autoridade e inovação no universo outdoor. Este plataforma de palestras oferece uma oportunidade ímpar de se conectar diretamente com um público apaixonado, compartilhando conhecimentos, experiências e valores que ressoam com a comunidade. Além de reforçar o posicionamento da sua marca, estimula o diálogo, a educação e a construção de uma relação mais profunda e significativa com os atletas e entusiastas.'),
    (supplier_60_id, 'Vídeo Telão', TRUE, 'Utilizar os telões do evento para exibir vídeos promocionais da sua marca é uma estratégia poderosa de ativação no Paraty Brazil by UTMB. Esta exposição em grande escala garante que sua mensagem alcance atletas, espectadores e participantes, criando um impacto visual memorável. É uma chance única de destacar sua marca, produtos ou iniciativas, engajando a audiência em tempo real e ampliando significativamente sua visibilidade durante momentos chave do evento.'),
    (supplier_60_id, 'After Movie', TRUE, 'O After Movie do Paraty Brazil by UTMB eterniza sua marca nos melhores momentos desta edição épica. Este vídeo, uma cápsula do tempo de triunfos e emoções, será compartilhado e revisto por uma audiência global, garantindo que sua marca seja lembrada não apenas como patrocinadora, mas como parte integral da história e do legado do evento.'),
    (supplier_60_id, 'Permuta', TRUE, 'A permuta oferece uma oportunidade estratégica para sua marca se envolver no Paraty Brazil by UTMB, permitindo o abatimento do valor de patrocínio mediante o fornecimento de produtos ou serviços. Esta abordagem enriquece a experiência dos participantes, destacando sua marca como um colaborador vital que contribui para o sucesso e a qualidade do evento.');
END $$;